// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241230081605_Seeding for data diff and region")]
    partial class Seedingfordatadiffandregion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NZWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = "100",
                            Code = "Akl",
                            Name = "Auckland",
                            RegionImageUrl = "Akl.img"
                        },
                        new
                        {
                            Id = "200",
                            Code = "Akl2",
                            Name = "Auckland2",
                            RegionImageUrl = "Akl2.img"
                        },
                        new
                        {
                            Id = "300",
                            Code = "Akl3",
                            Name = "Auckland3",
                            RegionImageUrl = "Akl3.img"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("LengthInKM")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WalkImageId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("WebApplication1.Models.Domain.Difficulty", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Difficulty");

                    b.HasData(
                        new
                        {
                            Id = "111",
                            Name = "Easy"
                        },
                        new
                        {
                            Id = "222",
                            Name = "Medium"
                        },
                        new
                        {
                            Id = "333",
                            Name = "Hard"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
